## The purpose of this notebook is to turn the datasets returned from the lag creator to be grouped by the day and add the features extracted for that day (average polarity and volume)

In [4]:
#imports
import pandas as pd

In [5]:
#get data with following lag
granularity = "days"
lag = 7
analyser = "TextBlob"
# analyser = "vader"

In [6]:
#prepare filename to read
folder = "./../datasets/tweets_and_prices/"+analyser+"/";
filename = folder+"/final_data_lag_"+granularity+"_"+str(lag)+".csv" if (lag > 0) else folder+"/final_data_no_lag.csv"

/Users/jacques/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [ ]:
#read data
df = pd.read_csv(filename)

In [7]:
df.head()

,Unnamed: 0,Unnamed: 0_x,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,timestamp,Unnamed: 0_y,id,user,fullname,url,replies,likes,retweets,text,polarity,subjectivity
0,0,3500001,6944.90,10.379585,72022.107341,6938.823172,2018-08-31 11:05:00+00:00,2637369,1.039500e+18,DolarTrue_,DolarTrue,/DolarTrue_/status/1039499938361565184,0.0,2.0,3.0,#DolarTrue BTC\n11/09/2018 09:04 AM\nBTC Venta...,0.0,0.0
1,1,3500004,6949.51,5.503697,38235.502385,6947.240108,2018-08-31 11:08:00+00:00,2637371,1.039501e+18,_digitalhouse,Digital House,/_digitalhouse/status/1039500792275890177,0.0,4.0,2.0,Los esperamos! Charla introductoria sobre Bloc...,0.0,0.0
2,2,3500008,6929.68,8.665554,60084.483521,6933.715284,2018-08-31 11:12:00+00:00,2637368,1.039502e+18,NowBitcoinPrice,Bitcoin Price Now,/NowBitcoinPrice/status/1039501879850553345,0.0,0.0,0.0,"Sep 11, 2018 13:11:00 UTC | 6,278.10$ | 5,422....",0.0,0.0
3,3,3500010,6936.15,3.883404,26944.988504,6938.496582,2018-08-31 11:14:00+00:00,2637367,1.039502e+18,T45Investments,T45 INVESTMENTS,/T45Investments/status/1039502432957546499,0.0,1.0,0.0,13.00 GMT Update!\n#trading #futures #commodit...,0.0,0.0
4,4,3500014,6938.09,0.636451,4416.054740,6938.565297,2018-08-31 11:18:00+00:00,2637365,1.039503e+18,Okwethu62750507,Okwethu,/Okwethu62750507/status/1039503450940301313,0.0,0.0,0.0,Sign up using my invite link and we’ll both re...,0.3,0.1

In [8]:
#remove extra columns
df = df.drop(['Unnamed: 0', 'Unnamed: 0_x',  'Unnamed: 0_y'], axis=1)

In [10]:
#copy dataframe so that we do not have to stay reloading data after changes
df_copy = df.copy()

In [11]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14918171 entries, 0 to 14918170
Data columns (total 15 columns):
 #   Column             Dtype
---  ------             -----
 0   Close              float64
 1   Volume_(BTC)       float64
 2   Volume_(Currency)  float64
 3   Weighted_Price     float64
 4   timestamp          object
 5   id                 float64
 6   user               object
 7   fullname           object
 8   url                object
 9   replies            float64
 10  likes              float64
 11  retweets           float64
 12  text               object
 13  polarity           float64
 14  subjectivity       float64
dtypes: float64(10), object(5)
memory usage: 1.7+ GB

In [12]:
#get datetime
df_copy["dt"] = pd.to_datetime(df_copy['timestamp'])
df_copy = df_copy.drop(['timestamp'], axis=1)

In [14]:
#floor datetimes to day
df_copy['DateTime'] = df_copy['dt'].dt.floor('d')

In [15]:
df_copy['DateTime']

0          2018-08-31 00:00:00+00:00
1          2018-08-31 00:00:00+00:00
2          2018-08-31 00:00:00+00:00
3          2018-08-31 00:00:00+00:00
4          2018-08-31 00:00:00+00:00
                      ...
14918166   2019-11-12 00:00:00+00:00
14918167   2019-11-12 00:00:00+00:00
14918168   2019-11-12 00:00:00+00:00
14918169   2019-11-12 00:00:00+00:00
14918170   2019-11-12 00:00:00+00:00
Name: DateTime, Length: 14918171, dtype: datetime64[ns, UTC]

In [16]:
#group tweet volumes daily
grouped_volumes = df_copy.groupby(pd.Grouper(key='dt',freq='d')).size().reset_index(name='tweet_vol')

In [17]:
#set index to datetime
grouped_volumes.index = pd.to_datetime(grouped_volumes.index)
grouped_volumes = grouped_volumes.set_index('dt')

In [18]:
#set type of volumes to float
grouped_volumes['tweet_vol'] = grouped_volumes['tweet_vol'].astype(float)

In [19]:
grouped_volumes.head()

                           tweet_vol
dt
2018-08-31 00:00:00+00:00      494.0
2018-09-01 00:00:00+00:00      924.0
2018-09-02 00:00:00+00:00      904.0
2018-09-03 00:00:00+00:00      874.0
2018-09-04 00:00:00+00:00      869.0
...                              ...
2019-03-14 00:00:00+00:00      830.0
2019-03-15 00:00:00+00:00      916.0
2019-03-16 00:00:00+00:00      905.0
2019-03-17 00:00:00+00:00     3027.0
2019-03-18 00:00:00+00:00      961.0

[200 rows x 1 columns]

In [22]:
#set datetime to index of dataframe
df_copy.index = pd.to_datetime(df_copy.index)

In [23]:
#group by day and take the average of values in that day
df_copy = df_copy.groupby('DateTime').agg(lambda x: x.mean())

In [24]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 439 entries, 2018-08-31 00:00:00+00:00 to 2019-11-12 00:00:00+00:00
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Close              439 non-null    float64
 1   Volume_(BTC)       439 non-null    float64
 2   Volume_(Currency)  439 non-null    float64
 3   Weighted_Price     439 non-null    float64
 4   id                 439 non-null    float64
 5   replies            439 non-null    float64
 6   likes              439 non-null    float64
 7   retweets           439 non-null    float64
 8   polarity           439 non-null    float64
 9   subjectivity       439 non-null    float64
 10  dt                 439 non-null    datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(10)
memory usage: 41.2 KB

In [26]:
#set DateTime 
df['DateTime'] = df['dt'].dt.floor('d')

In [27]:
#get final prices of day

#before
# df_copy["Close"] = pd.Series(df.loc[df.groupby('DateTime').dt.idxmax()]["Close"]).values
#new
df_copy["Close"] = pd.Series(df_copy.loc[df_copy.groupby('DateTime').dt.idxmax()]["Close"]).values

# df2["Open"] = pd.Series(df.loc[df.groupby('DateTime').dt.idxmin()]["Open"]).values
# df2["High"] = pd.Series(df.loc[df.groupby('DateTime').Close.idxmax()]["High"]).values
# df2["Low"] = pd.Series(df.loc[df.groupby('DateTime').Close.idxmin()]["Low"]).values

439
439

In [28]:
df_copy.tail()

,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,id,replies,likes,retweets,polarity,subjectivity,dt
DateTime,,,,,,,,,,,
2019-10-14 00:00:00+00:00,8311.99,3.271587,27190.454470,8301.865904,1.187716e+18,0.248893,2.676428,0.800016,0.090694,0.239811,2019-10-14 13:00:45.616171008+00:00
2019-10-15 00:00:00+00:00,8150.21,3.525739,29188.280595,8295.348373,1.188038e+18,0.301486,2.993298,0.775941,0.079677,0.228965,2019-10-15 10:22:43.704728576+00:00
2019-10-16 00:00:00+00:00,7977.13,6.611971,52999.422567,8067.752121,1.188435e+18,0.236166,2.295677,0.659967,0.096701,0.240368,2019-10-16 12:40:50.082236416+00:00
2019-10-17 00:00:00+00:00,8061.17,4.339115,34937.924583,8032.289508,1.188796e+18,0.202536,2.197100,0.756818,0.094979,0.241679,2019-10-17 12:32:43.048142080+00:00
2019-10-18 00:00:00+00:00,7953.45,4.089549,32428.159880,7961.831286,1.189160e+18,0.347839,2.367908,0.782356,0.101085,0.248512,2019-10-18 12:41:01.114417920+00:00
2019-10-19 00:00:00+00:00,7959.00,2.607976,20778.816625,7963.823278,1.189521e+18,0.284242,2.176971,0.744817,0.099606,0.252333,2019-10-19 12:34:31.301897472+00:00
2019-10-20 00:00:00+00:00,8212.40,4.790176,38705.336344,7998.195565,1.189886e+18,0.254511,2.481762,0.983024,0.109351,0.250378,2019-10-20 12:45:58.748639744+00:00
2019-10-21 00:00:00+00:00,8214.63,3.740850,30777.869436,8224.395997,1.190247e+18,0.268470,2.280110,0.991612,0.100883,0.241367,2019-10-21 12:37:34.916432384+00:00
2019-10-22 00:00:00+00:00,8095.00,4.042768,33180.735594,8214.503701,1.190608e+18,0.303307,2.096612,0.744565,0.096560,0.237335,2019-10-22 12:33:46.519044608+00:00
2019-10-23 00:00:00+00:00,7433.14,10.939623,83047.757878,7766.725227,1.190973e+18,0.244224,1.826423,0.630112,0.087219,0.234853,2019-10-23 12:42:35.240655360+00:00
2019-10-24 00:00:00+00:00,7442.89,4.177726,31093.160354,7450.312073,1.191340e+18,0.280446,2.397005,0.890487,0.092055,0.239631,2019-10-24 13:03:51.310296320+00:00
2019-10-25 00:00:00+00:00,8600.29,12.718629,103598.432462,7793.691749,1.191696e+18,0.289378,2.501925,0.854418,0.101135,0.249211,2019-10-25 12:36:11.319985152+00:00
2019-10-26 00:00:00+00:00,9250.00,26.267809,245284.544000,9261.586749,1.192058e+18,0.292286,2.158373,0.897695,0.097679,0.243078,2019-10-26 12:34:53.778146560+00:00
2019-10-27 00:00:00+00:00,9578.25,12.584349,119549.285455,9408.426167,1.192416e+18,0.282979,2.221760,0.905538,0.099785,0.248432,2019-10-27 12:16:27.534598400+00:00
2019-10-28 00:00:00+00:00,9459.03,9.466213,89874.152794,9460.219369,1.192785e+18,0.296042,2.391618,0.842601,0.089042,0.234908,2019-10-28 12:44:32.441779712+00:00
2019-10-29 00:00:00+00:00,9463.13,7.079978,66346.477122,9380.623428,1.193142e+18,0.248633,1.861675,0.639891,0.093433,0.246781,2019-10-29 12:22:15.022577664+00:00
2019-10-30 00:00:00+00:00,9231.39,6.742522,61720.853492,9188.976672,1.193511e+18,0.283411,1.920131,0.663492,0.086613,0.227466,2019-10-30 12:48:30.627992576+00:00
2019-10-31 00:00:00+00:00,9127.50,7.999751,73388.873525,9183.249803,1.193875e+18,0.303996,2.476470,1.124516,0.086386,0.229038,2019-10-31 12:56:26.545854464+00:00
2019-11-01 00:00:00+00:00,9204.47,4.939884,45262.080573,9153.480411,1.194233e+18,0.220523,2.009241,0.854780,0.088871,0.225069,2019-11-01 12:37:57.655103488+00:00
2019-11-02 00:00:00+00:00,9302.99,1.746202,16212.873435,9281.087847,1.194592e+18,0.289169,1.880198,0.770939,0.093948,0.235062,2019-11-02 12:24:21.605904384+00:00
2019-11-03 00:00:00+00:00,9214.70,1.966518,18071.063599,9212.616590,1.194957e+18,0.270615,2.340954,0.868827,0.094664,0.248293,2019-11-03 12:35:08.332583936+00:00
2019-11-04 00:00:00+00:00,9386.93,3.724068,34765.679196,9253.759819,1.195319e+18,0.248912,2.543746,0.780642,0.095526,0.249408,2019-11-04 12:35:08.990327040+00:00
2019-11-05 00:00:00+00:00,9325.93,3.774707,35167.176230,9343.633338,1.195678e+18,0.267465,1.504441,0.592314,0.095824,0.254041,2019-11-05 12:21:54.619798272+00:00
2019-11-06 00:00:00+00:00,9342.58,3.130159,29227.504308,9336.193707,1.196044e+18,0.237714,1.657513,0.671087,0.087990,0.236580,2019-11-06 12:35:49.779207168+00:00
2019-11-07 00:00:00+00:00,9220.13,3.192104,29452.890860,9233.167085,1.196415e+18,0.267925,1.933314,0.746239,0.082458,0.232727,2019-11-07 13:08:08.333464064+00:00
2019-11-08 00:00:00+00:00,8805.26,7.320433,65176.435394,8977.698091,1.196769e+18,0.239867,2.214188,0.735137,0.090353,0.245458,2019-11-08 12:36:24.966406656+00:00
2019-11-09 00:00:00+00:00,8801.12,2.178017,19186.377131,8810.220250,1.197131e+18,0.313149,2.042054,0.884736,0.102290,0.257392,2019-11-09 12:35:11.090065408+00:00
2019-11-10 00:00:00+00:00,9080.00,2.604415,23320.629147,8891.088876,1.197503e+18,0.339254,3.520410,1.148407,0.093208,0.254647,2019-11-10 13:10:37.389079040+00:00
2019-11-11 00:00:00+00:00,8709.30,4.961968,43347.940479,8779.937341,1.197861e+18,0.266415,1.908900,0.579354,0.081636,0.245228,2019-11-11 12:53:46.502249472+00:00
2019-11-12 00:00:00+00:00,8655.92,3.002157,26200.830198,8728.751305,1.198153e+18,0.114250,0.786511,0.289440,0.091571,0.243703,2019-11-12 08:13:41.509998592+00:00

In [29]:
#add tweet volume to df
df_copy['Tweet_vol'] = grouped_volumes['tweet_vol']

In [30]:
df_copy.head()

,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,id,replies,likes,retweets,polarity,subjectivity,dt,Tweet_vol
DateTime,,,,,,,,,,,,
2018-08-31 00:00:00+00:00,7027.99,11.135208,77449.019458,6978.914509,1.039593e+18,1.064777,16.103239,11.348178,0.040649,0.181438,2018-08-31 17:18:08.259111424+00:00,494.0
2018-09-01 00:00:00+00:00,7177.75,8.284260,59248.707244,7097.005264,1.039883e+18,0.732684,5.575758,2.614719,0.047416,0.180825,2018-09-01 12:31:44.285716480+00:00,924.0
2018-09-02 00:00:00+00:00,7275.00,2.113649,15273.666477,7233.231304,1.040238e+18,0.663717,10.097345,2.858407,0.059910,0.190780,2018-09-02 12:01:57.278758144+00:00,904.0
2018-09-03 00:00:00+00:00,7301.01,2.624572,19052.075231,7260.741470,1.040591e+18,1.299771,5.878719,2.885584,0.051803,0.180683,2018-09-03 11:22:44.004575744+00:00,874.0
2018-09-04 00:00:00+00:00,7350.00,3.245320,23714.036422,7313.477778,1.040953e+18,1.095512,31.539701,12.470656,0.040184,0.175435,2018-09-04 11:25:34.729575936+00:00,869.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-11-08 00:00:00+00:00,8805.26,7.320433,65176.435394,8977.698091,1.196769e+18,0.239867,2.214188,0.735137,0.090353,0.245458,2019-11-08 12:36:24.966406656+00:00,61530.0
2019-11-09 00:00:00+00:00,8801.12,2.178017,19186.377131,8810.220250,1.197131e+18,0.313149,2.042054,0.884736,0.102290,0.257392,2019-11-09 12:35:11.090065408+00:00,55785.0
2019-11-10 00:00:00+00:00,9080.00,2.604415,23320.629147,8891.088876,1.197503e+18,0.339254,3.520410,1.148407,0.093208,0.254647,2019-11-10 13:10:37.389079040+00:00,60462.0
2019-11-11 00:00:00+00:00,8709.30,4.961968,43347.940479,8779.937341,1.197861e+18,0.266415,1.908900,0.579354,0.081636,0.245228,2019-11-11 12:53:46.502249472+00:00,73941.0
2019-11-12 00:00:00+00:00,8655.92,3.002157,26200.830198,8728.751305,1.198153e+18,0.114250,0.786511,0.289440,0.091571,0.243703,2019-11-12 08:13:41.509998592+00:00,35510.0

In [32]:
#remove tweet id, retweets, likes, replies and currency volume
df_copy = df_copy.drop(['id', 'retweets', 'likes', 'replies', 'Volume_(Currency)'], axis=1)

In [33]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 439 entries, 2018-08-31 00:00:00+00:00 to 2019-11-12 00:00:00+00:00
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Close           439 non-null    float64
 1   Volume_(BTC)    439 non-null    float64
 2   Weighted_Price  439 non-null    float64
 3   polarity        439 non-null    float64
 4   subjectivity    439 non-null    float64
 5   dt              439 non-null    datetime64[ns, UTC]
 6   Tweet_vol       439 non-null    float64
dtypes: datetime64[ns, UTC](1), float64(6)
memory usage: 27.4 KB

In [ ]:
folder = "./../datasets/tweets_prices_volumes_sentiment/"+analyser+"/day_datasets/"

if not os.path.exists('my_folder'):
    os.makedirs('my_folder')

In [34]:
df_copy.to_csv(folder+"dataset_lag_"+granularity+"_"+str(lag)+".csv")